### ISSUE TITLE
RAM usage for planet bundle

### ISSUE THREAD

**Issue by tadjik1** [osmcode/node-osmium#103]
Hello there,
I'm experiencing problems with running `node-osmium` for planet bundle. Some time after I run script memory consumption grows to >30GB and my docker container stops.
My task is to process administrative regions so I'm using this code:
```
const osmium = require('osmium');

const file = new osmium.File(path.join(datapath, filename), 'pbf');
const filter = new osmium.Filter();
const location_handler = new osmium.LocationHandler('dense_mmap_array');

filter.with_areas();

const reader = new osmium.Reader(file, location_handler);
const stream = new osmium.Stream(reader, filter);

// consume stream chunk by chunk
```

Node.js: 10.16.0
node-osmium: 0.5.7
osmium: v2.14.0

Is it a problem with my code or with library itself?

**Comment by joto** [comment]
When you are using the `dense_mmap_array` you will need at least about 50 to 60 GB for that alone. That is entirely due to the amount of data that needs to be processed, in this case the location of all the OSM nodes which is stored in memory. There might be other problems in node-osmium and/or your script which lead to extra memory consumption.

And streaming the whole planet through node-osmium will take a long time. If you only need a small subset of the data, in this case only the administrative boundaries I strongly suggest that you use [osmium-tool](https://osmcode.org/osmium-tool) to pre-filter the planet for only the stuff you need (using the `tags-filter` command) and then use the result as input for your node-osmium code which can then use the `sparse_mmap_array` which needs a lot less memory for small amounts of data. Depending on what exactly you are filtering the osmium-tool task will still need a lot of memory, but in your case it should be definitely much less.
