### ISSUE TITLE
std::bad_alloc on long-running osmium.Stream

### ISSUE THREAD

**Issue by rclark** [osmcode/node-osmium#69]
On attempting to pass an entire planet pbf through an `osmium.Stream`, I'm consistently getting `std:bad_alloc` with the following log:

```
$ time osm2geojson /data/planet.osm.pbf > /dev/null

/home/rclark/osm2geojson/node_modules/osmium/lib/osmium.js:100
    return this._reader.read();
                        ^
Error: osmium error: std::bad_alloc
    at exports.Reader.read (/home/rclark/osm2geojson/node_modules/osmium/lib/osmium.js:100:25)
    at exports.Stream._read_object (/home/rclark/osm2geojson/node_modules/osmium/lib/osmium.js:194:37)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

real    61m47.498s
user    65m8.015s
sys     6m36.171s
```

The script is using node-osmium to read the pbf and convert data to geojson, and seems to work fine on smaller datasets: https://github.com/rclark/osm2geojson/blob/306450a6d677a7754f94494aa951fe731bf184dd/index.js

Let me know if there's any way I can help gather more information. Thanks!

**Comment by springmeyer** [comment]
`std::bad_alloc` usually indicates one of two things:

  - 1) memory was requested when the machine has become really low on memory
  - 2) a massive amount of memory was requested

2) can happen because of an integer overflow or other bug. 1) Is a common situation when a program is just loading to much into RAM.

I presume you are hitting 1) and you can confirm by just confirming that the node-osmium is using a lot of memory (GBs). If you are hitting 1) then I presume it means that the `osmium.Stream` interface is just not the right tool for the job and we should lean on @joto for recommendations of a better type of handler approach for the whole planet. (I presume he will recommend using a custom C++ script implemented on libosmium rather than via node-osmium).

**Comment by joto** [comment]
@springmeyer Yes, I will. :-) The details of memory management of NodeJS are intractable to me. Maybe somebody smarter can figure out what is happening there, but for the time being I expect nose-osmium to only be useful for smal extracts.

**Comment by springmeyer** [comment]
> for the time being I expect nose-osmium to only be useful for smal extracts.

:+1: Closing this issue therefore.
